// <auto-generated />
namespace Exhibition.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class isUpper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isUpper));
        
        string IMigrationMetadata.Id
        {
            get { return "201810301138322_isUpper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
